// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyInventory2026.src.shared.context;

#nullable disable

namespace MyInventory2026.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408222602_ErdProvidersProducts")]
    partial class ErdProvidersProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyInventory2026.src.modules.product.Infrastructure.entity.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeInv")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codeInv");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nameProduct");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<int>("StockMax")
                        .HasColumnType("int")
                        .HasColumnName("stck_max");

                    b.Property<int>("StockMin")
                        .HasColumnType("int")
                        .HasColumnName("stock_min");

                    b.HasKey("Id");

                    b.HasIndex("CodeInv")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("MyInventory2026.src.modules.provider.Infrastructure.entity.ProviderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nameProvider");

                    b.HasKey("Id");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("MyInventory2026.src.shared.context.ProviderProductEntity", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("provider_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.HasKey("ProviderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("provider_products", (string)null);
                });

            modelBuilder.Entity("MyInventory2026.src.shared.context.ProviderProductEntity", b =>
                {
                    b.HasOne("MyInventory2026.src.modules.product.Infrastructure.entity.ProductEntity", "Product")
                        .WithMany("ProviderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyInventory2026.src.modules.provider.Infrastructure.entity.ProviderEntity", "Provider")
                        .WithMany("ProviderProducts")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("MyInventory2026.src.modules.product.Infrastructure.entity.ProductEntity", b =>
                {
                    b.Navigation("ProviderProducts");
                });

            modelBuilder.Entity("MyInventory2026.src.modules.provider.Infrastructure.entity.ProviderEntity", b =>
                {
                    b.Navigation("ProviderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
